from __future__ import annotations

from typing import Any
from uuid import UUID, uuid4

from app.db.supabase import get_admin_client


ALERT_THRESHOLD = 70.0


def _safe_float(value: Any) -> float | None:
    try:
        return float(value) if value is not None else None
    except (TypeError, ValueError):
        return None


def _level_score(level: float | None, warning: float | None, danger: float | None, hfl: float | None) -> float:
    if level is None or warning is None or danger is None:
        return 0.0
    if level < warning:
        return 0.0
    if hfl is None or hfl <= danger:
        if level >= danger:
            return 60.0
        fraction = (level - warning) / max(danger - warning, 1e-9)
        return round(20.0 + max(0.0, min(1.0, fraction)) * 40.0, 2)
    if level < danger:
        fraction = (level - warning) / max(danger - warning, 1e-9)
        return round(20.0 + max(0.0, min(1.0, fraction)) * 20.0, 2)
    if level < hfl:
        fraction = (level - danger) / max(hfl - danger, 1e-9)
        return round(40.0 + max(0.0, min(1.0, fraction)) * 20.0, 2)
    return 60.0


def _rate_score(rate_m_hr: float | None) -> float:
    if rate_m_hr is None or rate_m_hr <= 0:
        return 0.0

    if rate_m_hr <= 0.02:
        return 10.0

    return 20.0


def _risk(total: float) -> tuple[str, str, bool]:
    if total < 25:
        return "normal", "P3", False
    if total < 50:
        return "watch", "P3", False
    if total < 70:
        return "warning", "P2", False
    if total < 85:
        return "high", "P1", True
    return "critical", "P0", True


def _hazard_from_report(report_type: str) -> str:
    if report_type in {"flood", "water_rise"}:
        return "flash_flood"
    if report_type == "landslide":
        return "landslide"
    if report_type == "avalanche":
        return "avalanche"
    return "unknown"


def _find_or_create_event(station: dict, hazard_type: str) -> dict:
    admin = get_admin_client()
    basin_id = station.get("basin_id")
    if basin_id:
        existing = (
            admin.table("events")
            .select("*")
            .eq("basin_id", str(basin_id))
            .eq("hazard_type", hazard_type)
            .in_("status", ["monitoring", "active", "confirmed"])
            .order("created_at", desc=True)
            .limit(1)
            .execute()
            .data
        )
        if existing:
            return existing[0]

    event_code = f"AUTO-{station['station_code']}-{hazard_type.upper()}-{uuid4().hex[:8]}"
    payload = {
        "event_code": event_code,
        "hazard_type": hazard_type,
        "title": f"Potential {hazard_type.replace('_', ' ').title()} at {station['station_name']}",
        "description": "Generated by CascadeGuard rule engine",
        "latitude": station.get("latitude"),
        "longitude": station.get("longitude"),
        "basin_id": station.get("basin_id"),
        "first_observed_at": None,
        "last_observed_at": None,
        "confidence_score": 0,
        "confidence_level": "suspected",
        "status": "active",
    }
    response = admin.table("events").insert(payload).select("*").execute()
    if not response.data:
        raise ValueError("Failed to create event")
    return response.data[0]


def _get_station(station_id: UUID | str) -> dict:
    admin = get_admin_client()
    response = (
        admin.table("hydro_stations")
        .select("*")
        .eq("id", str(station_id))
        .single()
        .execute()
    )
    if not response.data:
        raise ValueError("Station not found")
    return response.data


def _get_previous_hydro_rows(
    station_id: UUID | str,
    current_observed_at: str | None = None
) -> list[dict]:
    admin = get_admin_client()

    query = (
        admin.table("hydro_readings")
        .select("id,observed_at,water_level_m")
        .eq("station_id", str(station_id))
    )

    # Only consider readings that happened before the current reading.
    if current_observed_at:
        query = query.lt("observed_at", current_observed_at)

    rows = (
        query
        .order("observed_at", desc=True)
        .limit(2)
        .execute()
        .data
        or []
    )

    return rows


def _get_recent_confirming_sensor(station_id: UUID | str) -> dict | None:
    admin = get_admin_client()
    rows = (
        admin.table("sensor_readings")
        .select("*")
        .order("observed_at", desc=True)
        .limit(20)
        .execute()
        .data
        or []
    )
    # Prototype association: station-specific linkage is supplied by the ingestion route
    # through metadata when the current sensor is the one being evaluated.
    for row in rows:
        metadata = row.get("raw_data") or {}
        if str(metadata.get("station_id")) == str(station_id):
            return row
    return None


def _get_recent_community_report(station_id: UUID | str) -> dict | None:
    admin = get_admin_client()
    rows = (
        admin.table("community_reports")
        .select("*")
        .eq("station_id", str(station_id))
        .order("submitted_at", desc=True)
        .limit(5)
        .execute()
        .data
        or []
    )
    for row in rows:
        if row.get("verification_status") in {"pending", "verified"}:
            return row
    return None


def evaluate_hydro_reading(
    hydro_reading: dict,
    sensor_reading: dict | None = None,
    community_report: dict | None = None,
    create_alert: bool = True,
) -> dict:
    station = _get_station(hydro_reading["station_id"])

    level = _safe_float(hydro_reading.get("water_level_m"))
    rate = _safe_float(hydro_reading.get("water_level_rate_m_hr"))

    level_score = _level_score(
        level,
        _safe_float(station.get("warning_level_m")),
        _safe_float(station.get("danger_level_m")),
        _safe_float(station.get("highest_flood_level_m")),
    )
    rate_score = _rate_score(rate)

    sensor_score = 0.0
    if sensor_reading:
        sensor_type = sensor_reading.get("sensor_type")
        sensor_value = _safe_float(sensor_reading.get("numeric_value"))
        if sensor_type == "water_level" and sensor_value is not None:
            warning = _safe_float(station.get("warning_level_m"))
            if warning is not None and sensor_value >= warning:
                sensor_score = 10.0
        elif sensor_type in {"seismic", "vibration", "camera"}:
            sensor_score = 5.0

    community_score = 0.0

    if community_report:
        report_type = community_report.get("report_type")
        verification_status = community_report.get("verification_status")

        if (
            report_type in {"flood", "water_rise", "landslide", "avalanche"}
            and verification_status == "verified"
        ):
            community_score = 5.0

    previous = _get_previous_hydro_rows(
    hydro_reading["station_id"],
    hydro_reading.get("observed_at")
)
    warning = _safe_float(station.get("warning_level_m"))
    persistence_score = 5.0 if warning is not None and len(previous) >= 2 and all(
        _safe_float(row.get("water_level_m")) is not None and _safe_float(row.get("water_level_m")) >= warning
        for row in previous[:2]
    ) else 0.0

    total = min(100.0, round(level_score + rate_score + sensor_score + community_score + persistence_score, 2))
    risk_level, priority, alert_recommended = _risk(total)

    reasons: list[str] = []
    if level_score > 0:
        reasons.append(f"River level contributes {level_score:.1f}/60")
    if rate_score > 0:
        reasons.append(f"Rate of rise contributes {rate_score:.1f}/20")
    if sensor_score > 0:
        reasons.append(f"Sensor confirmation contributes {sensor_score:.1f}/10")
    if community_score > 0:
        reasons.append(f"Community evidence contributes {community_score:.1f}/5")
    if persistence_score > 0:
        reasons.append("Consecutive abnormal readings add persistence evidence")
    if not reasons:
        reasons.append("No abnormal evidence crossed the scoring rules")

    event = None
    if total >= 50:
        event = _find_or_create_event(station, "flash_flood")

        admin = get_admin_client()
        update_payload = {
            "last_observed_at": hydro_reading.get("observed_at"),
            "confidence_score": total,
            "confidence_level": "confirmed" if total >= 70 else "probable",
            "status": "confirmed" if total >= 70 else "active",
            "updated_at": hydro_reading.get("observed_at"),
        }
        admin.table("events").update(update_payload).eq("id", event["id"]).execute()

        evidence = {
            "event_id": event["id"],
            "source_id": station.get("source_id"),
            "feed_ingestion_id": None,
            "observation_type": "river_level",
            "is_supporting_evidence": True,
        }
        admin.table("event_observations").insert(evidence).execute()

    evaluation_payload = {
        "hydro_reading_id": hydro_reading.get("id"),
        "sensor_reading_id": (sensor_reading or {}).get("id"),
        "community_report_id": (community_report or {}).get("id"),
        "event_id": event.get("id") if event else None,
        "engine_version": "v1.0",
        "level_score": level_score,
        "rate_score": rate_score,
        "sensor_score": sensor_score,
        "community_score": community_score,
        "persistence_score": persistence_score,
        "total_score": total,
        "risk_level": risk_level,
        "alert_recommended": alert_recommended,
        "alert_priority": priority,
        "reasons": reasons,
        "input_snapshot": {
            "station": station,
            "hydro_reading": hydro_reading,
            "sensor_reading": sensor_reading,
            "community_report": community_report,
        },
    }
    evaluation_response = (
        get_admin_client()
        .table("rule_evaluations")
        .insert(evaluation_payload)
        .select("*")
        .execute()
    )
    if not evaluation_response.data:
        raise ValueError("Failed to create rule evaluation")
    evaluation = evaluation_response.data[0]

    alert = None
    if alert_recommended and create_alert and event:
        alert = _create_pending_alert(event, station, evaluation, priority)

    return {
        "evaluation": evaluation,
        "event": event,
        "alert": alert,
        "risk_level": risk_level,
        "total_score": total,
        "alert_recommended": alert_recommended,
        "alert_priority": priority,
        "reasons": reasons,
    }


def evaluate_sensor_reading(
    sensor_reading: dict,
    station_id: UUID | str,
) -> dict:
    admin = get_admin_client()

    # Get the latest historical hydro reading for the station.
    hydro_rows = (
        admin.table("hydro_readings")
        .select("*")
        .eq("station_id", str(station_id))
        .order("observed_at", desc=True)
        .limit(1)
        .execute()
        .data
        or []
    )

    if not hydro_rows:
        # Create evaluation context only.
        # This synthetic row is NOT inserted into hydro_readings.
        hydro = {
            "id": None,
            "station_id": str(station_id),
            "observed_at": None,
            "water_level_m": None,
            "water_level_rate_m_hr": None,
            "data_mode": "live",
        }
    else:
        hydro = hydro_rows[0]

    # sensor_readings stores sensor_id, while sensor_type
    # is stored in sensor_devices.
    sensor_type = None

    sensor_id = sensor_reading.get("sensor_id")

    if sensor_id:
        device_rows = (
            admin.table("sensor_devices")
            .select("sensor_type")
            .eq("id", str(sensor_id))
            .limit(1)
            .execute()
            .data
            or []
        )

        if device_rows:
            sensor_type = device_rows[0].get("sensor_type")

    # Copy the sensor reading and add the sensor type
    # so evaluate_hydro_reading() can apply the correct rule.
    sensor_copy = dict(sensor_reading)
    sensor_copy["sensor_type"] = sensor_type

    raw = dict(sensor_copy.get("raw_data") or {})
    raw["station_id"] = str(station_id)
    raw["sensor_code"] = raw.get(
        "sensor_code",
        sensor_copy.get("sensor_code"),
    )

    sensor_copy["raw_data"] = raw

    return evaluate_hydro_reading(
        hydro,
        sensor_reading=sensor_copy,
    )


def evaluate_community_report(report: dict) -> dict:
    station_id = report["station_id"]
    admin = get_admin_client()
    hydro_rows = (
        admin.table("hydro_readings")
        .select("*")
        .eq("station_id", str(station_id))
        .order("observed_at", desc=True)
        .limit(1)
        .execute()
        .data
        or []
    )
    hydro = hydro_rows[0] if hydro_rows else {
        "id": None,
        "station_id": str(station_id),
        "observed_at": None,
        "water_level_m": None,
        "water_level_rate_m_hr": None,
        "data_mode": "live",
    }
    return evaluate_hydro_reading(hydro, community_report=report)


def _create_pending_alert(event: dict, station: dict, evaluation: dict, priority: str) -> dict:
    admin = get_admin_client()
    existing = (
        admin.table("alerts")
        .select("*")
        .eq("event_id", event["id"])
        .in_("status", ["draft", "pending_approval", "approved", "dispatching", "active"])
        .order("created_at", desc=True)
        .limit(1)
        .execute()
        .data
        or []
    )
    if existing:
        return existing[0]

    score = _safe_float(evaluation.get("total_score")) or 0
    payload = {
        "alert_code": f"CG-{station['station_code']}-{evaluation['id'][:8]}",
        "event_id": event["id"],
        "cap_identifier": f"cascadeguard-{evaluation['id']}",
        "message_type": "Alert",
        "scope": "restricted",
        "hazard_type": event.get("hazard_type"),
        "title": f"CascadeGuard warning — {station['river_name']}",
        "description": f"Rule engine confidence score: {score:.1f}/100 at {station['station_name']}",
        "instruction": "Follow local disaster-management instructions and move toward the designated safe area if directed.",
        "priority": priority,
        "urgency": "Immediate" if priority in {"P0", "P1"} else "Expected",
        "severity": "Extreme" if priority == "P0" else "Severe" if priority == "P1" else "Moderate",
        "certainty": "Observed",
        "status": "pending_approval",
        "cap_payload": {"prototype": True, "generated_by": "rule_engine", "evaluation_id": evaluation["id"]},
    }
    response = admin.table("alerts").insert(payload).select("*").execute()
    if not response.data:
        raise ValueError("Failed to create alert")
    return response.data[0]
